'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, CalendarClock, MailCheck, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { authFetch } from '@/lib/auth-client';

type Appointment = { id: string; startsAt: string; status: string; customerName: string; staffName: string; serviceName: string };
type Data = { appointments: Appointment[]; error?: string };
const field = 'h-11 w-full rounded-xl border border-white/12 bg-[#15243a] px-3 text-sm text-[#eaf1fb] outline-none';

export default function ReschedulePage() {
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [appointmentId, setAppointmentId] = useState(''); const [slots, setSlots] = useState(['', '', '']); const [error, setError] = useState(''); const [status, setStatus] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { authFetch('/api/appointments').then(async (response) => { const payload = await response.json() as Data; if (!response.ok) throw new Error(payload.error || 'Could not load appointments.'); setAppointments(payload.appointments.filter((item) => !['cancelled', 'completed'].includes(item.status))); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Could not load appointments.')); }, []);
  const send = async () => { setError(''); setStatus(''); const options = slots.filter(Boolean).map((value) => new Date(value).toISOString()); if (!appointmentId || options.length < 2) { setError('Choose an appointment and at least two future time choices.'); return; } setSaving(true); try { const response = await authFetch('/api/reschedule-offers', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ appointmentId, options }) }); const payload = await response.json() as { delivery?: string; error?: string }; if (!response.ok) throw new Error(payload.error || 'Could not send the choices.'); setStatus(payload.delivery === 'email_sent' ? 'A personal time-choice email was sent. The customer can pick one option directly from the link.' : 'The private choice link was created, but this customer has no deliverable email address.'); setSlots(['', '', '']); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not send the choices.'); } finally { setSaving(false); } };
  return <main className="min-h-screen bg-[#07111f] text-[#eaf1fb]"><section className="mx-auto max-w-3xl px-5 py-10"><button onClick={() => window.location.assign('/workspace')} className="flex items-center gap-2 text-sm text-[#91a6bf] hover:text-white"><ArrowLeft size={16} /> Back to Command Center</button><div className="mt-8 rounded-3xl border border-white/9 bg-[#0d1a2d] p-6 sm:p-9"><div className="flex items-start gap-4"><span className="grid size-12 place-items-center rounded-2xl bg-[#17375e] text-[#85b7ff]"><CalendarClock /></span><div><p className="text-xs font-bold tracking-[.16em] text-[#85b7ff]">SMART RESCHEDULE</p><h1 className="mt-2 text-3xl font-black">Offer real choices, not a generic message.</h1><p className="mt-3 max-w-xl leading-7 text-[#a9bad0]">Choose an appointment and propose 2–4 times. The customer gets a personal, single-use link and their selected time updates the schedule automatically.</p></div></div><div className="mt-8 space-y-4"><label className="block text-sm font-semibold">Appointment<select value={appointmentId} onChange={(event) => setAppointmentId(event.target.value)} className={`${field} mt-2`}><option value="">Choose appointment</option>{appointments.map((item) => <option key={item.id} value={item.id}>{item.customerName} · {item.serviceName} · {new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(item.startsAt))}</option>)}</select></label>{slots.map((slot, index) => <label key={index} className="block text-sm font-semibold">{index === 0 ? 'First proposed time' : index === 1 ? 'Second proposed time' : 'Optional third proposed time'}<input type="datetime-local" value={slot} onChange={(event) => setSlots(slots.map((current, i) => i === index ? event.target.value : current))} className={`${field} mt-2`} /></label>)}<Button onClick={send} disabled={saving} className="h-12 w-full bg-[#4c8df6] text-white"><MailCheck className="mr-2" size={18} />{saving ? 'Sending choices…' : 'Send secure time choices'}</Button>{status && <p className="rounded-xl border border-[#62e2b5]/25 bg-[#163b36]/50 px-4 py-3 text-sm text-[#b7f3dc]">{status}</p>}{error && <p className="rounded-xl bg-red-500/10 px-4 py-3 text-sm text-red-200">{error}</p>}</div><div className="mt-7 flex items-start gap-3 rounded-2xl border border-white/8 bg-white/[.03] p-4 text-sm text-[#a9bad0]"><ShieldCheck className="mt-0.5 shrink-0 text-[#62e2b5]" size={18} />Links expire after 48 hours and cannot overwrite another appointment. If a slot has just been taken, the customer sees the remaining choices.</div></div></section></main>;
}
