'use client';

import { useEffect, useState } from 'react';
import { CalendarClock, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';

type Option = { startsAt: string; endsAt: string };
type Offer = { firstName: string; serviceName: string; businessName: string; options: Option[]; error?: string };

export default function RescheduleChoicePage() {
  const [token, setToken] = useState(''); const [offer, setOffer] = useState<Offer | null>(null); const [selected, setSelected] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [done, setDone] = useState('');
  useEffect(() => { const value = window.location.pathname.split('/').filter(Boolean).pop() || ''; setToken(value); fetch(`/api/reschedule-offers?token=${encodeURIComponent(value)}`).then(async (response) => { const payload = await response.json() as Offer; if (!response.ok) throw new Error(payload.error || 'This link is unavailable.'); setOffer(payload); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'This link is unavailable.')); }, []);
  const submit = async () => { setSaving(true); setError(''); try { const response = await fetch('/api/reschedule-offers', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token, startsAt: selected }) }); const payload = await response.json() as { startsAt?: string; error?: string }; if (!response.ok) throw new Error(payload.error || 'We could not save that time.'); setDone(payload.startsAt || selected); } catch (cause) { setError(cause instanceof Error ? cause.message : 'We could not save that time.'); } finally { setSaving(false); } };
  if (error) return <main className="grid min-h-screen place-items-center bg-[#07111f] p-6 text-center text-[#eaf1fb]"><div><CalendarClock className="mx-auto text-[#85b7ff]" size={38} /><h1 className="mt-4 text-2xl font-bold">Time selection unavailable</h1><p className="mt-2 text-[#a9bad0]">{error}</p></div></main>;
  if (!offer) return <main className="grid min-h-screen place-items-center bg-[#07111f] text-[#a9bad0]">Opening your time choices…</main>;
  if (done) return <main className="grid min-h-screen place-items-center bg-[#07111f] p-6 text-center text-[#eaf1fb]"><div className="max-w-md rounded-3xl border border-[#62e2b5]/30 bg-[#0d1a2d] p-9"><CheckCircle2 className="mx-auto text-[#62e2b5]" size={42} /><h1 className="mt-5 text-2xl font-bold">Your new time is confirmed.</h1><p className="mt-3 leading-7 text-[#a9bad0]">{new Intl.DateTimeFormat(undefined, { dateStyle: 'full', timeStyle: 'short' }).format(new Date(done))}</p><p className="mt-3 text-sm text-[#a9bad0]">{offer.businessName} has been notified.</p></div></main>;
  return <main className="min-h-screen bg-[#07111f] px-5 py-12 text-[#eaf1fb]"><section className="mx-auto max-w-xl rounded-3xl border border-white/9 bg-[#0d1a2d] p-6 sm:p-9"><div className="grid size-12 place-items-center rounded-2xl bg-[#17375e] text-[#85b7ff]"><CalendarClock /></div><p className="mt-6 text-xs font-bold tracking-[.16em] text-[#85b7ff]">MARACITA TIME CHOICE</p><h1 className="mt-3 text-3xl font-black">Choose the time that suits you.</h1><p className="mt-3 leading-7 text-[#a9bad0]">Hi {offer.firstName}, {offer.businessName} has proposed a new time for your {offer.serviceName}.</p><div className="mt-8 space-y-3">{offer.options.map((option) => <button key={option.startsAt} type="button" onClick={() => setSelected(option.startsAt)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === option.startsAt ? 'border-[#85b7ff] bg-[#17375e]/70' : 'border-white/10 bg-white/[.03] hover:border-[#85b7ff]/60'}`}><b className="block text-white">{new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date(option.startsAt))}</b><span className="mt-1 block text-sm text-[#a9bad0]">{new Intl.DateTimeFormat(undefined, { hour: '2-digit', minute: '2-digit' }).format(new Date(option.startsAt))}</span></button>)}</div><Button disabled={!selected || saving} onClick={submit} className="mt-7 h-12 w-full bg-[#4c8df6] text-white">{saving ? 'Confirming…' : 'Confirm this time'}</Button>{error && <p className="mt-4 rounded-xl bg-red-500/10 px-4 py-3 text-sm text-red-200">{error}</p>}</section></main>;
}
