'use client';

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import { Globe2 } from 'lucide-react';

export type Locale = 'en' | 'he' | 'ar' | 'fr' | 'ru' | 'es';
export const languages: { code: Locale; label: string }[] = [
  { code: 'en', label: 'English' }, { code: 'he', label: 'עברית' }, { code: 'ar', label: 'العربية' },
  { code: 'fr', label: 'Français' }, { code: 'ru', label: 'Русский' }, { code: 'es', label: 'Español' },
];

type Dictionary = Record<string, string>;
const dictionaries: Record<Exclude<Locale, 'en'>, Dictionary> = {
  he: { 'Language':'שפה','Account & Language':'חשבון ושפה','Save language preference':'שמירת העדפת שפה','Language preference':'העדפת שפה','Back to Command Center':'חזרה למרכז הבקרה','COMMAND CENTER':'מרכז הבקרה','Your workspace':'סביבת העבודה שלך','Open →':'פתיחה ←','New appointment':'תור חדש','3-day trial active':'ניסיון ל־3 ימים פעיל','Setup Studio':'הגדרת העסק','Customers':'לקוחות','Smart Schedule':'יומן חכם','FlowMap':'מפת זרימה','Payments':'תשלומים','Payments & Receipts':'תשלומים וקבלות','Analytics Lab':'מרכז ניתוחים','Smart Waitlist':'רשימת המתנה חכמה','Help Center':'מרכז עזרה','Team members':'חברי צוות','Active bookings':'תורים פעילים','Flow signals':'התראות זרימה','Create appointment':'קביעת תור','Appointment timeline':'ציר זמן של תורים','Select customer':'בחירת לקוח','Select team member':'בחירת חבר צוות','Select service':'בחירת שירות','Notes (optional)':'הערות (אופציונלי)','Creating…':'יוצר…','Scheduled':'נקבע','Confirmed':'מאושר','Arrived':'הגיע','Completed':'הושלם','Cancelled':'בוטל','No-show':'לא הגיע','Add customer':'הוספת לקוח','First name':'שם פרטי','Last name':'שם משפחה','Phone':'טלפון','Email (optional)':'אימייל (אופציונלי)','Search name, phone or tag':'חיפוש שם, טלפון או תגית','Add team member':'הוספת חבר צוות','Add service':'הוספת שירות','Full name':'שם מלא','Service name':'שם השירות','Duration':'משך','Buffer':'מרווח','Service catalog':'קטלוג שירותים','Team & specialists':'צוות ומומחים','Record payment':'רישום תשלום','Payment history':'היסטוריית תשלומים','Add to waitlist':'הוספה לרשימת המתנה','Waiting':'ממתין','Offered':'הוצע','Filled':'מולא','Closed':'נסגר','Refresh data':'רענון נתונים','Sign in':'התחברות','Sign up':'הרשמה','Forgot password?':'שכחת סיסמה?','Back':'חזרה','Continue':'המשך','Business name':'שם העסק','Email address':'כתובת אימייל','Password':'סיסמה','Your full name':'השם המלא שלך','Messages':'הודעות','Customer conversation':'שיחת לקוח','Send message':'שליחת הודעה','Attach file':'צירוף קובץ','Print receipt':'הדפסת קבלה' },
  ar: { 'Language':'اللغة','Account & Language':'الحساب واللغة','Save language preference':'حفظ اللغة','Language preference':'تفضيل اللغة','Back to Command Center':'العودة إلى مركز التحكم','COMMAND CENTER':'مركز التحكم','Your workspace':'مساحة عملك','Open →':'فتح ←','New appointment':'موعد جديد','3-day trial active':'تجربة 3 أيام مفعّلة','Setup Studio':'إعداد العمل','Customers':'العملاء','Smart Schedule':'الجدول الذكي','FlowMap':'خريطة التدفق','Payments':'المدفوعات','Payments & Receipts':'المدفوعات والإيصالات','Analytics Lab':'مختبر التحليلات','Smart Waitlist':'قائمة الانتظار الذكية','Help Center':'مركز المساعدة','Team members':'أعضاء الفريق','Active bookings':'الحجوزات النشطة','Flow signals':'إشارات التدفق','Create appointment':'إنشاء موعد','Appointment timeline':'الجدول الزمني للمواعيد','Select customer':'اختر عميلاً','Select team member':'اختر عضو فريق','Select service':'اختر خدمة','Notes (optional)':'ملاحظات (اختياري)','Creating…':'جارٍ الإنشاء…','Scheduled':'مجدول','Confirmed':'مؤكد','Arrived':'وصل','Completed':'مكتمل','Cancelled':'ملغى','No-show':'لم يحضر','Add customer':'إضافة عميل','First name':'الاسم الأول','Last name':'اسم العائلة','Phone':'الهاتف','Email (optional)':'البريد الإلكتروني (اختياري)','Search name, phone or tag':'ابحث بالاسم أو الهاتف أو الوسم','Add team member':'إضافة عضو فريق','Add service':'إضافة خدمة','Full name':'الاسم الكامل','Service name':'اسم الخدمة','Duration':'المدة','Buffer':'فاصل','Service catalog':'كتالوج الخدمات','Team & specialists':'الفريق والمختصون','Record payment':'تسجيل دفعة','Payment history':'سجل المدفوعات','Add to waitlist':'إضافة إلى قائمة الانتظار','Waiting':'بانتظار','Offered':'تم العرض','Filled':'تم الملء','Closed':'مغلق','Refresh data':'تحديث البيانات','Sign in':'تسجيل الدخول','Sign up':'إنشاء حساب','Forgot password?':'هل نسيت كلمة المرور؟','Back':'رجوع','Continue':'متابعة','Business name':'اسم العمل','Email address':'البريد الإلكتروني','Password':'كلمة المرور','Your full name':'اسمك الكامل','Messages':'الرسائل','Customer conversation':'محادثة العميل','Send message':'إرسال رسالة','Attach file':'إرفاق ملف','Print receipt':'طباعة الإيصال' },
  fr: { 'Language':'Langue','Account & Language':'Compte et langue','Save language preference':'Enregistrer la langue','Language preference':'Préférence de langue','Back to Command Center':'Retour au centre de contrôle','COMMAND CENTER':'CENTRE DE CONTRÔLE','Your workspace':'Votre espace de travail','Open →':'Ouvrir →','New appointment':'Nouveau rendez-vous','3-day trial active':'Essai de 3 jours actif','Setup Studio':'Configuration','Customers':'Clients','Smart Schedule':'Planning intelligent','FlowMap':'Carte de flux','Payments':'Paiements','Payments & Receipts':'Paiements et reçus','Analytics Lab':'Analyses','Smart Waitlist':'Liste d’attente intelligente','Help Center':'Centre d’aide','Team members':'Membres de l’équipe','Active bookings':'Réservations actives','Flow signals':'Signaux de flux','Create appointment':'Créer un rendez-vous','Appointment timeline':'Chronologie des rendez-vous','Select customer':'Sélectionner un client','Select team member':'Sélectionner un membre','Select service':'Sélectionner un service','Notes (optional)':'Notes (facultatif)','Creating…':'Création…','Scheduled':'Planifié','Confirmed':'Confirmé','Arrived':'Arrivé','Completed':'Terminé','Cancelled':'Annulé','No-show':'Absent','Add customer':'Ajouter un client','First name':'Prénom','Last name':'Nom','Phone':'Téléphone','Email (optional)':'E-mail (facultatif)','Search name, phone or tag':'Rechercher un nom, téléphone ou tag','Add team member':'Ajouter un membre','Add service':'Ajouter un service','Full name':'Nom complet','Service name':'Nom du service','Duration':'Durée','Buffer':'Marge','Service catalog':'Catalogue de services','Team & specialists':'Équipe et spécialistes','Record payment':'Enregistrer le paiement','Payment history':'Historique des paiements','Add to waitlist':'Ajouter à la liste d’attente','Waiting':'En attente','Offered':'Proposé','Filled':'Pourvu','Closed':'Fermé','Refresh data':'Actualiser les données','Sign in':'Se connecter','Sign up':'S’inscrire','Forgot password?':'Mot de passe oublié ?','Back':'Retour','Continue':'Continuer','Business name':'Nom de l’entreprise','Email address':'Adresse e-mail','Password':'Mot de passe','Your full name':'Votre nom complet','Messages':'Messages','Customer conversation':'Conversation client','Send message':'Envoyer le message','Attach file':'Joindre un fichier','Print receipt':'Imprimer le reçu' },
  ru: { 'Language':'Язык','Account & Language':'Аккаунт и язык','Save language preference':'Сохранить язык','Language preference':'Настройка языка','Back to Command Center':'Назад в центр управления','COMMAND CENTER':'ЦЕНТР УПРАВЛЕНИЯ','Your workspace':'Ваше рабочее пространство','Open →':'Открыть →','New appointment':'Новая запись','3-day trial active':'Пробный период 3 дня активен','Setup Studio':'Настройка бизнеса','Customers':'Клиенты','Smart Schedule':'Умное расписание','FlowMap':'Карта потока','Payments':'Платежи','Payments & Receipts':'Платежи и квитанции','Analytics Lab':'Аналитика','Smart Waitlist':'Умный список ожидания','Help Center':'Центр помощи','Team members':'Члены команды','Active bookings':'Активные записи','Flow signals':'Сигналы потока','Create appointment':'Создать запись','Appointment timeline':'Хронология записей','Select customer':'Выберите клиента','Select team member':'Выберите сотрудника','Select service':'Выберите услугу','Notes (optional)':'Заметки (необязательно)','Creating…':'Создание…','Scheduled':'Запланировано','Confirmed':'Подтверждено','Arrived':'Прибыл','Completed':'Завершено','Cancelled':'Отменено','No-show':'Не явился','Add customer':'Добавить клиента','First name':'Имя','Last name':'Фамилия','Phone':'Телефон','Email (optional)':'Эл. почта (необязательно)','Search name, phone or tag':'Поиск по имени, телефону или тегу','Add team member':'Добавить сотрудника','Add service':'Добавить услугу','Full name':'Полное имя','Service name':'Название услуги','Duration':'Длительность','Buffer':'Интервал','Service catalog':'Каталог услуг','Team & specialists':'Команда и специалисты','Record payment':'Записать платёж','Payment history':'История платежей','Add to waitlist':'В список ожидания','Waiting':'Ожидание','Offered':'Предложено','Filled':'Заполнено','Closed':'Закрыто','Refresh data':'Обновить данные','Sign in':'Войти','Sign up':'Регистрация','Forgot password?':'Забыли пароль?','Back':'Назад','Continue':'Продолжить','Business name':'Название бизнеса','Email address':'Эл. почта','Password':'Пароль','Your full name':'Ваше полное имя','Messages':'Сообщения','Customer conversation':'Диалог с клиентом','Send message':'Отправить сообщение','Attach file':'Прикрепить файл','Print receipt':'Распечатать квитанцию' },
  es: { 'Language':'Idioma','Account & Language':'Cuenta e idioma','Save language preference':'Guardar idioma','Language preference':'Preferencia de idioma','Back to Command Center':'Volver al centro de control','COMMAND CENTER':'CENTRO DE CONTROL','Your workspace':'Tu espacio de trabajo','Open →':'Abrir →','New appointment':'Nueva cita','3-day trial active':'Prueba de 3 días activa','Setup Studio':'Configuración','Customers':'Clientes','Smart Schedule':'Agenda inteligente','FlowMap':'Mapa de flujo','Payments':'Pagos','Payments & Receipts':'Pagos y recibos','Analytics Lab':'Análisis','Smart Waitlist':'Lista de espera inteligente','Help Center':'Centro de ayuda','Team members':'Miembros del equipo','Active bookings':'Reservas activas','Flow signals':'Señales de flujo','Create appointment':'Crear cita','Appointment timeline':'Cronología de citas','Select customer':'Seleccionar cliente','Select team member':'Seleccionar miembro','Select service':'Seleccionar servicio','Notes (optional)':'Notas (opcional)','Creating…':'Creando…','Scheduled':'Programada','Confirmed':'Confirmada','Arrived':'Ha llegado','Completed':'Completada','Cancelled':'Cancelada','No-show':'No asistió','Add customer':'Añadir cliente','First name':'Nombre','Last name':'Apellido','Phone':'Teléfono','Email (optional)':'Correo (opcional)','Search name, phone or tag':'Buscar nombre, teléfono o etiqueta','Add team member':'Añadir miembro','Add service':'Añadir servicio','Full name':'Nombre completo','Service name':'Nombre del servicio','Duration':'Duración','Buffer':'Margen','Service catalog':'Catálogo de servicios','Team & specialists':'Equipo y especialistas','Record payment':'Registrar pago','Payment history':'Historial de pagos','Add to waitlist':'Añadir a la lista de espera','Waiting':'En espera','Offered':'Ofrecido','Filled':'Cubierto','Closed':'Cerrado','Refresh data':'Actualizar datos','Sign in':'Iniciar sesión','Sign up':'Registrarse','Forgot password?':'¿Olvidaste tu contraseña?','Back':'Atrás','Continue':'Continuar','Business name':'Nombre del negocio','Email address':'Correo electrónico','Password':'Contraseña','Your full name':'Tu nombre completo','Messages':'Mensajes','Customer conversation':'Conversación con cliente','Send message':'Enviar mensaje','Attach file':'Adjuntar archivo','Print receipt':'Imprimir recibo' },
};

type ContextType = { locale: Locale; setLocale: (locale: Locale) => void };
const I18nContext = createContext<ContextType | null>(null);
const ignored = 'script,style,[data-i18n-ignore]';
// Keep the original English source outside the effect so switching languages repeatedly is reversible.
const textOriginals = new WeakMap<Text, string>();
const attrOriginals = new WeakMap<Element, Record<string, string>>();
function translate(source: string, locale: Locale) { if (locale === 'en') return source; const leading = source.match(/^\s*/)?.[0] ?? ''; const trailing = source.match(/\s*$/)?.[0] ?? ''; return `${leading}${dictionaries[locale][source.trim()] ?? source.trim()}${trailing}`; }

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>('en');
  const setLocale = useCallback((next: Locale) => { setLocaleState(next); localStorage.setItem('maracita.locale', next); }, []);
  useEffect(() => { const stored = localStorage.getItem('maracita.locale') as Locale | null; if (stored && languages.some((language) => language.code === stored)) setLocaleState(stored); }, []);
  useEffect(() => {
    document.documentElement.lang = locale; document.documentElement.dir = locale === 'he' || locale === 'ar' ? 'rtl' : 'ltr';
    const apply = (root: Node) => {
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); let node: Node | null;
      while ((node = walker.nextNode())) { const text = node as Text; if (text.parentElement?.closest(ignored)) continue; const original = textOriginals.get(text) ?? text.nodeValue ?? ''; textOriginals.set(text, original); text.nodeValue = translate(original, locale); }
      const roots = root instanceof Element ? [root, ...Array.from(root.querySelectorAll('*'))] : Array.from(document.querySelectorAll('*'));
      roots.forEach((element) => { if (element.closest(ignored)) return; const remembered = attrOriginals.get(element) ?? {}; ['placeholder', 'aria-label', 'title'].forEach((attribute) => { const now = element.getAttribute(attribute); if (now !== null && remembered[attribute] === undefined) remembered[attribute] = now; if (remembered[attribute] !== undefined) element.setAttribute(attribute, translate(remembered[attribute], locale)); }); attrOriginals.set(element, remembered); });
    };
    apply(document.body); const observer = new MutationObserver((records) => records.forEach((record) => record.addedNodes.forEach(apply))); observer.observe(document.body, { childList: true, subtree: true }); return () => observer.disconnect();
  }, [locale]);
  const value = useMemo(() => ({ locale, setLocale }), [locale, setLocale]);
  return <I18nContext.Provider value={value}>{children}<label data-i18n-ignore className="fixed end-5 top-3 z-50 flex h-9 items-center gap-2 rounded-lg border border-white/12 bg-[#0d1a2d]/95 px-2 text-xs font-semibold text-white shadow-lg backdrop-blur"><Globe2 size={15} className="text-[#85b7ff]" /><select aria-label="Language" value={locale} onChange={(event) => setLocale(event.target.value as Locale)} className="max-w-24 bg-transparent outline-none"><option value="en">English</option><option value="he">עברית</option><option value="ar">العربية</option><option value="fr">Français</option><option value="ru">Русский</option><option value="es">Español</option></select></label></I18nContext.Provider>;
}

export function useI18n() { const context = useContext(I18nContext); if (!context) throw new Error('Missing language provider.'); return context; }
