'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, Globe2, ShieldCheck, UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Locale, useI18n } from '@/components/i18n-provider';

type Account = { fullName: string; email: string; preferredLocale: string };
const languages = [
  { code: 'en', label: 'English', native: 'English' }, { code: 'he', label: 'Hebrew', native: 'עברית' }, { code: 'ar', label: 'Arabic', native: 'العربية' }, { code: 'fr', label: 'French', native: 'Français' }, { code: 'ru', label: 'Russian', native: 'Русский' }, { code: 'es', label: 'Spanish', native: 'Español' },
];

export default function AccountPage() {
  const { locale, setLocale } = useI18n(); const [account, setAccount] = useState<Account | null>(null); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/account').then(async (r) => { const p = await r.json() as { account?: Account; error?: string }; if (!r.ok || !p.account) throw new Error(p.error || 'Could not open account.'); setAccount(p.account); setLocale(p.account.preferredLocale as Locale); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Could not open account.')); }, [setLocale]);
  const save = async () => { setNotice(''); setError(''); try { const r = await fetch('/api/account', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ locale }) }); const p = await r.json() as { error?: string }; if (!r.ok) throw new Error(p.error || 'Could not save language.'); setNotice('Language preference saved for this account.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save language.'); } };
  if (!account) return <main className="grid min-h-screen place-items-center bg-[#07111f] text-[#a9bad0]">{error || 'Opening account settings…'}</main>;
  return <main className="min-h-screen bg-[#07111f] text-[#eaf1fb]"><header className="border-b border-white/8 bg-[#091526]"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><button onClick={() => window.location.assign('/workspace')} className="flex items-center gap-2 font-extrabold tracking-[.08em]"><span className="grid size-8 place-items-center rounded-xl bg-gradient-to-br from-[#62a7ff] to-[#7257f6]">M</span>MARACITA</button><span className="text-sm text-[#9db0c6]">Account & Language</span></div></header><section className="mx-auto max-w-4xl px-5 py-10"><button onClick={() => window.location.assign('/workspace')} className="flex items-center gap-2 text-sm text-[#91a6bf] hover:text-white"><ArrowLeft size={16} /> Back to Command Center</button><div className="mt-8 grid gap-6 md:grid-cols-[.8fr_1.2fr]"><aside className="rounded-2xl border border-white/9 bg-[#0d1a2d] p-6"><span className="grid size-11 place-items-center rounded-xl bg-[#17375e] text-[#85b7ff]"><UserRound /></span><h1 className="mt-5 text-2xl font-bold">{account.fullName}</h1><p className="mt-2 text-sm text-[#9db0c6]">{account.email}</p><div className="mt-8 rounded-xl border border-white/7 bg-white/[.03] p-4"><div className="flex gap-3"><ShieldCheck className="shrink-0 text-[#62e2b5]" size={19} /><p className="text-sm leading-6 text-[#b5c6d9]">This preview uses a protected development session. A public password and reset-email provider will be connected before launch.</p></div></div></aside><section className="rounded-2xl border border-white/9 bg-[#0d1a2d] p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#283351] text-[#c3a0ff]"><Globe2 /></span><div><h2 className="text-xl font-bold">Language preference</h2><p className="text-sm text-[#9db0c6]">Saved to your account across sessions.</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{languages.map((language) => <button key={language.code} onClick={() => setLocale(language.code as Locale)} className={`rounded-xl border p-4 text-left ${locale === language.code ? 'border-[#5b99fa] bg-[#1a3458]' : 'border-white/10 bg-white/[.03] hover:bg-white/[.06]'}`}><p className="font-semibold text-white">{language.native}</p><p className="mt-1 text-sm text-[#9db0c6]">{language.label}</p></button>)}</div><Button onClick={save} className="mt-7 h-11 w-full bg-[#4c8df6] text-white">Save language preference</Button>{notice && <p className="mt-4 rounded-xl bg-[#163b36] px-4 py-3 text-sm text-[#8ef0ca]">{notice}</p>}{error && <p className="mt-4 rounded-xl bg-red-500/10 px-4 py-3 text-sm text-red-200">{error}</p>}</section></div></section></main>;
}
