'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowUpRight, BellRing, Check, CircleDollarSign, Clock3, Flame, HeartHandshake, Inbox, Loader2, Radar, ShieldCheck, Sparkles, UsersRound } from 'lucide-react';
import { Button } from '@/components/ui/button';

type Match = { id: string; name: string; phone: string; contactPreference: string };
type RescueItem = { id: string; signalType: string; priority: string; summary: string; createdAt: string; context: { customerName?: string; serviceName?: string; staffName?: string; startsAt?: string; matches?: Match[] } };
type Data = { items: RescueItem[]; pulse: { waiting: number; pendingPayments: number; todayBookings: number }; error?: string };

const tone = (priority: string) => priority === 'high'
  ? { dot: 'bg-[#ff7a6e]', chip: 'border-[#ff7a6e]/30 bg-[#ff7a6e]/10 text-[#ffb7af]', label: 'Immediate' }
  : { dot: 'bg-[#ffc266]', chip: 'border-[#ffc266]/30 bg-[#ffc266]/10 text-[#ffdca0]', label: 'Review' };

export default function SmartRescuePage() {
  const [data, setData] = useState<Data | null>(null);
  const [error, setError] = useState('');
  const [working, setWorking] = useState<string | null>(null);
  const load = async () => {
    const response = await fetch('/api/rescue', { cache: 'no-store' });
    const payload = await response.json() as Data;
    if (!response.ok) throw new Error(payload.error || 'Could not load Smart Rescue.');
    setData(payload);
  };
  useEffect(() => { load().catch((cause) => setError(cause instanceof Error ? cause.message : 'Could not load Smart Rescue.')); }, []);
  const resolve = async (id: string) => {
    setWorking(id); setError('');
    try {
      const response = await fetch('/api/rescue', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id }) });
      const payload = await response.json() as { error?: string };
      if (!response.ok) throw new Error(payload.error || 'Could not complete this item.');
      await load();
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not complete this item.'); }
    finally { setWorking(null); }
  };
  const urgent = useMemo(() => data?.items.filter((item) => item.priority === 'high').length ?? 0, [data]);
  if (!data) return <main className="grid min-h-screen place-items-center bg-[#0b0b0f] text-[#a7a89d]">{error || 'Scanning for rescue opportunities…'}</main>;
  const go = (path: string) => window.location.assign(path);
  return <main className="min-h-screen overflow-hidden bg-[#0b0b0f] text-[#f4f5ed]"><div className="maracita-grid pointer-events-none fixed inset-0 opacity-50" /><header className="relative border-b border-white/10 bg-[#0b0b0f]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><button onClick={() => go('/workspace')} className="flex items-center gap-3 font-extrabold tracking-[.12em]"><span className="signal-orb grid size-9 place-items-center rounded-full bg-[#c9f66b] text-sm text-[#10120d]">M</span>MARACITA</button><div className="flex items-center gap-2 text-xs font-bold tracking-[.12em] text-[#a7a89d]"><Radar size={15} className="text-[#c9f66b]" /> SMART RESCUE</div></div></header>
    <section className="relative mx-auto max-w-7xl px-5 py-8 lg:px-8"><button onClick={() => go('/workspace')} className="flex items-center gap-2 text-sm text-[#a7a89d] transition hover:text-white"><ArrowLeft size={16} /> Back to Home</button>
      <div className="mt-8 grid gap-5 lg:grid-cols-[1.12fr_.88fr]"><section className="relative overflow-hidden rounded-[2rem] border border-[#c9f66b]/18 bg-[#15151b]/92 p-7 md:p-9"><div className="absolute -right-16 -top-16 size-56 rounded-full bg-[#c9f66b]/10 blur-3xl" /><div className="relative"><p className="flex items-center gap-2 text-xs font-bold tracking-[.17em] text-[#c9f66b]"><Flame size={15} /> DECISION SPACE</p><h1 className="mt-4 max-w-xl text-4xl font-black tracking-tight text-white md:text-5xl">Save the day before it gets messy.</h1><p className="mt-4 max-w-xl text-base leading-7 text-[#b1b3a7]">Smart Rescue turns cancellations, waiting clients and unfinished payments into one calm decision queue.</p><div className="mt-8 flex flex-wrap gap-3"><span className="rounded-full border border-[#ff7a6e]/30 bg-[#ff7a6e]/10 px-4 py-2 text-sm font-bold text-[#ffb7af]">{urgent} urgent signal{urgent === 1 ? '' : 's'}</span><span className="rounded-full border border-white/10 bg-white/[.035] px-4 py-2 text-sm text-[#d9dad2]">{data.items.length} open action{data.items.length === 1 ? '' : 's'}</span></div></div></section>
        <section className="grid gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 sm:grid-cols-3">{[{ label: 'Waiting clients', value: data.pulse.waiting, icon: UsersRound, color: 'text-[#c9f66b]' }, { label: 'Payment follow-ups', value: data.pulse.pendingPayments, icon: CircleDollarSign, color: 'text-[#ffc266]' }, { label: 'Today in flow', value: data.pulse.todayBookings, icon: Clock3, color: 'text-[#c3a0ff]' }].map(({ label, value, icon: Icon, color }) => <article key={label} className="min-h-40 bg-[#15151b]/95 p-5"><Icon className={color} size={20} /><p className="mt-8 text-4xl font-black text-white">{value}</p><p className="mt-1 text-sm text-[#a7a89d]">{label}</p></article>)}</section></div>
      <div className="mt-8 grid gap-5 lg:grid-cols-[1fr_.45fr]"><section className="rounded-[2rem] border border-white/10 bg-[#15151b]/92 p-5 md:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[.17em] text-[#a7a89d]">LIVE ACTION QUEUE</p><h2 className="mt-2 text-2xl font-bold text-white">The next best move</h2></div><span className="flex items-center gap-2 text-sm text-[#c9f66b]"><span className="size-2 rounded-full bg-[#c9f66b]" /> Watching your workflow</span></div>
        <div className="mt-6 space-y-3">{data.items.length ? data.items.map((item) => { const style = tone(item.priority); const isMatch = item.signalType === 'waitlist_match'; const matches = item.context.matches || []; return <article key={item.id} className="group rounded-2xl border border-white/9 bg-black/15 p-5 transition hover:border-white/18"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`size-2 rounded-full ${style.dot}`} /><span className={`rounded-full border px-2.5 py-1 text-xs font-bold ${style.chip}`}>{style.label}</span><span className="text-xs font-bold tracking-[.12em] text-[#a7a89d]">{isMatch ? 'OPEN SLOT MATCH' : 'CUSTOMER FOLLOW-UP'}</span></div><h3 className="mt-3 text-lg font-bold text-white">{item.summary}</h3>{item.context.serviceName && <p className="mt-2 text-sm text-[#a7a89d]">{item.context.serviceName}{item.context.staffName ? ` · ${item.context.staffName}` : ''}{item.context.startsAt ? ` · ${new Intl.DateTimeFormat(undefined, { weekday: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(item.context.startsAt))}` : ''}</p>}{isMatch && matches.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{matches.slice(0, 3).map((match) => <span key={match.id} className="rounded-full border border-[#c9f66b]/20 bg-[#c9f66b]/[.06] px-3 py-1.5 text-sm text-[#e4f7b8]">{match.name}</span>)}{matches.length > 3 && <span className="rounded-full border border-white/10 px-3 py-1.5 text-sm text-[#a7a89d]">+{matches.length - 3} more</span>}</div>}</div><div className="flex shrink-0 flex-wrap gap-2"><Button onClick={() => go(isMatch ? '/workspace/waitlist' : '/workspace/messages')} className="h-10 rounded-full bg-[#c9f66b] px-4 text-[#10120d] hover:bg-[#ddff96]">{isMatch ? 'Review matches' : 'Prepare follow-up'} <ArrowUpRight size={16} /></Button><Button variant="outline" disabled={working === item.id} onClick={() => resolve(item.id)} className="h-10 rounded-full border-white/15 bg-transparent px-4 text-white hover:bg-white/8 hover:text-white">{working === item.id ? <Loader2 className="animate-spin" size={16} /> : <Check size={16} />} Done</Button></div></div></article>; }) : <div className="rounded-2xl border border-dashed border-white/12 px-6 py-14 text-center"><ShieldCheck className="mx-auto text-[#c9f66b]" size={30} /><h3 className="mt-4 font-bold text-white">Your rescue queue is clear</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-[#a7a89d]">New cancellations, waitlist matches and paid-service surveys will arrive here automatically.</p></div>}</div></section>
        <aside className="space-y-5"><section className="rounded-[2rem] border border-white/10 bg-[#15151b]/92 p-6"><div className="grid size-11 place-items-center rounded-2xl bg-[#c3a0ff]/13 text-[#c3a0ff]"><Sparkles size={21} /></div><h2 className="mt-5 text-xl font-bold text-white">Rescue logic</h2><div className="mt-5 space-y-4 text-sm leading-6 text-[#b1b3a7]"><p><b className="text-white">Cancellation:</b> finds the closest matching customer in the waitlist.</p><p><b className="text-white">Paid completion:</b> prepares a feedback follow-up for the customer.</p><p><b className="text-white">Action only:</b> nothing is sent or changed until you choose it.</p></div></section><button onClick={() => go('/workspace/waitlist')} className="group w-full rounded-[2rem] border border-[#ffc266]/20 bg-gradient-to-br from-[#34291a] to-[#15151b] p-6 text-left"><div className="flex items-center justify-between"><BellRing className="text-[#ffc266]" /><ArrowUpRight className="text-[#ffc266] transition group-hover:translate-x-1 group-hover:-translate-y-1" /></div><h2 className="mt-8 text-xl font-bold text-white">Keep the day full</h2><p className="mt-2 text-sm leading-6 text-[#d6c8ae]">Open the waitlist and add customers who want an earlier slot.</p></button><button onClick={() => go('/workspace/messages')} className="group w-full rounded-[2rem] border border-white/10 bg-[#15151b]/92 p-6 text-left"><Inbox className="text-[#76b8ff]" /><h2 className="mt-5 text-lg font-bold text-white">Customer messages</h2><p className="mt-1 text-sm text-[#a7a89d]">Prepare a personal follow-up with files and history.</p></button></aside></div>{error && <p className="mt-5 rounded-xl border border-red-400/20 bg-red-500/10 px-4 py-3 text-sm text-red-100">{error}</p>}</section></main>;
}
