'use client';

import { ArrowLeft, BadgeHelp, CalendarDays, CreditCard, Lightbulb, MessageCircleMore, Settings2, Users } from 'lucide-react';

const guides = [
  { icon: Settings2, title: '1. Set up your business', detail: 'Open Setup Studio. Add every staff member, then add the services you offer with their duration, buffer time and price.' },
  { icon: Users, title: '2. Add customers', detail: 'Open Customers and create a profile with a name and phone number. Tags and notes help your team remember useful context.' },
  { icon: CalendarDays, title: '3. Create and manage appointments', detail: 'Use Smart Schedule to choose a customer, team member, service and time. The system blocks overlapping appointments for the same team member. Change the status when the customer arrives, completes, cancels or does not show.' },
  { icon: Lightbulb, title: '4. Keep cancellations productive', detail: 'Use Smart Waitlist for customers who can take an earlier appointment. When a slot opens, update their status from Waiting to Offered, Filled or Closed.' },
  { icon: CreditCard, title: '5. Record a payment', detail: 'Use Payments to create a local payment record and receipt. This preview does not charge a card or transfer money — real payment processing is connected before public launch.' },
  { icon: MessageCircleMore, title: '6. Keep customer conversations together', detail: 'Open Messages, choose a customer and send a private note or attach a file up to 1 MB. The conversation is stored with that customer profile.' },
];

export default function HelpPage() {
  return <main className="min-h-screen bg-[#07111f] text-[#eaf1fb]"><header className="border-b border-white/8 bg-[#091526]"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><button onClick={() => window.location.assign('/workspace')} className="flex items-center gap-2 font-extrabold tracking-[.08em]"><span className="grid size-8 place-items-center rounded-xl bg-gradient-to-br from-[#62a7ff] to-[#7257f6]">M</span>MARACITA</button><span className="text-sm text-[#9db0c6]">Help Center</span></div></header><section className="mx-auto max-w-5xl px-5 py-10"><button onClick={() => window.location.assign('/workspace')} className="flex items-center gap-2 text-sm text-[#91a6bf] hover:text-white"><ArrowLeft size={16} /> Back to Command Center</button><div className="mt-8 rounded-2xl border border-white/9 bg-gradient-to-br from-[#102743] to-[#0d1a2d] p-7 sm:p-10"><span className="grid size-12 place-items-center rounded-2xl bg-[#17375e] text-[#85b7ff]"><BadgeHelp size={26} /></span><p className="mt-6 text-xs font-bold tracking-[.16em] text-[#70a8ff]">GET STARTED</p><h1 className="mt-2 text-3xl font-black text-white">Run your business in Maracita</h1><p className="mt-3 max-w-2xl text-base leading-7 text-[#b6c7dc]">Set up the people and services first, then add customers and appointments. Your dashboard, FlowMap and Analytics Lab update from those saved records.</p></div><div className="mt-7 space-y-4">{guides.map(({ icon: Icon, title, detail }) => <article key={title} className="flex gap-4 rounded-2xl border border-white/9 bg-[#0d1a2d] p-6"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white/5 text-[#85b7ff]"><Icon size={20} /></span><div><h2 className="font-bold text-white">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#a9bad0]">{detail}</p></div></article>)}</div><section className="mt-7 rounded-2xl border border-amber-300/15 bg-amber-300/[.06] p-6"><h2 className="font-bold text-[#ffe0a0]">Before public launch</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#d9c99f]">Public sign-in and password recovery, full language translation, a real payment provider, privacy documents and business testing are required before customers should use Maracita commercially.</p></section></section></main>;
}
